litex-hub/linux-on-litex-vexriscv

arty.py
The Arty and Versa builds have their own build output directories, but arty.py uses the "build" directory instead of the "build_arty" directory.
=> Use build_arty directory for loading and flashing

buildroot/board/litex_vexriscv/litex_vexriscv_arty.dts
The system clock frequency is 100 MHz not 75 MHz.
=> Fix timebase-frequency in .dts for Arty.

buildroot/board/litex_vexriscv/litex-vexriscv-linux.dtsi
@enjoy-digital 
Sorry,  but the commit 5e0fe1b4f27f ('dts: use feasable model and compatible strings, drop sifive mentions') "throws the baby out with the bathwater". It drops necessary "simple-bus" 'compatible' value together with SiFive-related values. As a result liteeth driver is never probed.
This PR fixes the problem.
=> fixup 'make liteeth work' PR

README.md
newer builds break a clean build. rv32 is broken on linux-5.1.
=> force buildroot commit rev to 982a61b6adabbcd68a0eb9ad1e348a732915e9e4

buildroot/board/litex_vexriscv/litex_vexriscv_arty.dts, buildroot/board/litex_vexriscv/litex_vexriscv_de0nano.dts, buildroot/board/litex_vexriscv/litex_vexriscv_genesys2.dts, buildroot/board/litex_vexriscv/litex_vexriscv_kcu105.dts, buildroot/board/litex_vexriscv/litex_vexriscv_minispartan6.dts, buildroot/board/litex_vexriscv/litex_vexriscv_netv2.dts, buildroot/board/litex_vexriscv/litex_vexriscv_nexys4ddr.dts, buildroot/board/litex_vexriscv/litex_vexriscv_ulx3s.dts, buildroot/board/litex_vexriscv/litex_vexriscv_versa_ecp5.dts
When adding litex_liteuart driver, it has only
been referenced in `litex_vexriscv.dts`. This commit
updtes other board-specific dts files.
=> linux: litex_liteuart: switch to liteuart in dts

make.py
Add the [Hackaday Supercon 2019 badge](https://hackaday.io/project/167255-2019-hackaday-superconference-badge) which has an ECP5 FPGA.
These changes are from [a fork](https://github.com/mwelling/linux-on-litex-vexriscv) by Michael Welling (@mwelling)
During Supercon, we tried two approaches:
- use the built-in 16MB QSPI SRAM
- use add-on cartiridge with 32MB SDRAM by Jacob Creedon
We were not able to get the QSPI SRAM working so I've removed those changes, and I have just added the changes that are needed to boot Linux with the 32MB SDRAM.
In addition to @mwelling, thank you to Jacob Creedon (@jcreedon), @GregDavill, Tim Ansell (@mithro), and Sean Cross (@xobs) who all helped get Linux working on this badge.
KiCad design files by @jcreedon for the SDRAM cartridge are [available on …
=> add the Hackaday Supercon ECP5 badge

soc_linux.py
Means when commands fail they will raise an exception.
Fixes #76.
=> Use subprocess.check_cal rather than os.system

buildroot/board/litex_vexriscv/patches/linux/0014-Add-litex-soc-controller.patch
The patch has been targetting a different
kernel commit and it didn't apply nicely
on 5.0.13
=> Fix SoC controller patch

soc_linux.py
=> soc_linux: fix max_sdram_size value

sim.py
This updates SDRAM support to use `l2_reverse` parameter and fixes an issue with `--sdram-data-width` argument being passed as a string.
Closes #84
Depends on enjoy-digital/litex#373 and depends on enjoy-digital/litedram#124
Closes enjoy-digital/litex#355
=> Update SDRAM support

sim.py
Same as 76fe0db4028d5ce1a8eb33ed02d8fd3a7348c421 but for simulations.
=> sim: add sdram size limit

.sim-test.py, .travis.yml, conda/environment.yml, conda/requirements.txt
Simulations pass with https://github.com/litex-hub/linux-on-litex-vexriscv/pull/96 and https://github.com/litex-hub/linux-on-litex-vexriscv/pull/100 applied.
Failures for Arty, Versa ECP5, or NeTV2 reported in https://github.com/litex-hub/linux-on-litex-vexriscv/issues/101.
=> travis: add simulated sdram test

make.py
SPIFLASH_PAGE_SIZE. SPIFLASH_SECTOR_SIZE and dummy bytes is working ok for the Hackaday Badge (ECP5).
LiteX BIOS can read the SPI Flash ok:
```
litex> mr 0xd0000000 128
Memory dump:
0xd0000000  00 50 61 72 74 3a 20 4c 46 45 35 55 2d 34 35 46  .Part: LFE5U-45F
0xd0000010  2d 38 43 41 42 47 41 33 38 31 00 ff ff ff bd b3  -8CABGA381......
0xd0000020  ff ff ff ff 3b 00 00 00 e2 00 00 00 41 11 20 43  ....;.......A. C
0xd0000030  22 00 00 00 40 00 00 00 46 00 00 00 82 91 24 fe  "...@...F.....$.
0xd0000040  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0xd0000050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0xd0000060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0xd0000070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 …
```
=> confirm SPI flash settings for HADBadge

emulator/Makefile, emulator/main.c
The changes are required because LiteX software
is now built with LTO (Linker Time Optimization).
For details see: https://github.com/enjoy-digital/litex/pull/401.
=> emulator: enable LTO

make.py
Depends on litex-hub/litex-boards#47
At this point LiteDRAM can only use half of the data bus (32-bit instead of 64-bit) but after disabling the other half Linux boots successfully on this board
=> make: add ZCU104 board

emulator/main.c, emulator/riscv.h
In trying to boot a v5.8 kernel, it seems that the kernel is attempting to discover the SBI version using the SBI_EXT_BASE syscall, but this is resulting in a hung board due to the default case in the SBI syscall hander doing a litex_stop(). I think the kernel is expecting the SBI syscall to return an error if not supported in this case.
This patch should workaround the issue in two ways: first we implement the SBI_EXT_BASE syscall to report our version as v0.1, and we also change the default case to return an error instead of halting the CPU.
=> emulator: Implement SBI_EXT_BASE syscall.

sim.py
When running the simulator in the project directory, as instructed by
README.md:
$ ./sim.py
...
Traceback (most recent call last):
File "./sim.py", line 242, in <module>
main()
File "./sim.py", line 236, in main
soc.generate_dts(board_name)
File "./sim.py", line 176, in generate_dts
with open(json_src) as json_file, open(dts, "w") as dts_file:
FileNotFoundError: [Errno 2] No such file or directory: 'build/sim/csr.json'
Due to the os.chdir(), the current directory is changed to the parent
directory of the project, and the csr.json file cannot be found.
Fix this dropping the os.chdir() call.
Fixes: acffa47e621e11f8 ("add dts auto-generation with litex json export and initial json2dts.py script")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
=> sim: Fix csr.json not found error

make.py
When building for OrangeCrab:
$ ./make.py --board=orangecrab --build
...
Traceback (most recent call last):
File "./make.py", line 492, in <module>
main()
File "./make.py", line 431, in main
soc = SoCLinux(board.soc_cls, **soc_kwargs)
File "/path/to/linux-on-litex-vexriscv/soc_linux.py", line 283, in SoCLinux
return _SoCLinux(**kwargs)
File "/path/to/linux-on-litex-vexriscv/soc_linux.py", line 111, in __init__
**kwargs)
File "/path/to/litex/litex-boards/litex_boards/targets/orangecrab.py", line 166, in __init__
self.submodules.crg = crg_cls(platform, sys_clk_freq, with_usb_pll)
File "/path/to/litex/litex-boards/litex_boards/targets/orangecrab.py", line 137, in __init__
reset_timer = WaitTimer(sys_clk_freq)
File "/path/to/litex/migen/migen/genlib/misc.py", line 83, in __init__
count = …
=> make: OrangeCrab: Fix sys_clk_freq

README.md, make.py
=> add Qmtech EP4CE15 coreboard support

make.py
Enable I2C on the Feather expansion connector, so Linux can access
I2C devices on FeatherWings.
Example i2cdetect output with Adafruit 0.54" Quad Alphanumeric
FeatherWing Display installed:
root@buildroot:~# i2cdetect -y -a 0
0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
root@buildroot:~#
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
=> make/orangecrab: Enable I2C

make.py
Hi,
This is a proposed colorlight i5 board support. Tested with booting litex-rebase branch HEAD of linux-hub/linux on nfsroot. Although 8MB RAM makes it hard to use as a normal linux system, it seems to make sense as a target for testing purposes.
Regards,
kaz
=> make.py: Add colorlight i5 board support

make.py
Hi,
This fixes the loading issue on colorlight i5 which is similar to
https://github.com/litex-hub/litex-boards/pull/169#issue-566422928
Regards,
kaz
=> make/colorlight_i5: set bitstream_ext to .bit instead of .svf.

README.md
The repo seems to have moved, adjust the clone URL (even though the old
one redirects).
=> README: adjust repo URL in git clone command

make.py
Formerly this caused a type error in `openocd.py`:
```
File ".../litex/linux-on-litex-vexriscv/./make.py", line 30, in flash
prog.flash(None, filename)
File ".../litex/litex/litex/build/openocd.py", line 36, in flash
"jtagspi_program {{{}}} 0x{:x}".format(data, address),
TypeError: unsupported format string passed to NoneType.__format__
```
=> make.py: fix flash

make.py, soc_linux.py
FPGA development boards typically have many expansion connectors, while
the board DTS as generated by LiteX describes only a part of the
system.
Add support for describing hardware connected to expansion connectors
using Flattened Device Tree Overlays.
Generation of the final DTB is done in two steps:
1. Compile the board DTS into a board DTB, with or without symbols,
depending on the presence of overlays,
2. Combine the board DTB and all specified overlays (if any) into the
final rv32.dtb using fdtoverlay.
If no overlays are specified, a shortcut is taken by just copying
the DTB, to avoid relying on the fdtoverlay tool being installed.
Example:
./make.py --board=orangecrab --cpu-count=1 --load --fdtoverlays="adafruit-featherwing-quad-alphanumeric-red.dtbo adafruit-featherwing-oled.dtbo" …
=> make/soc_linux: Add support for FDT Overlays

make.py
To iterate over key/value pairs from a dict, .items() must be used.
=> make: Fix soc_constants handling

soc_linux.py
That PR adds interrupt to switches in soc_linux.py and is associated with issue: https://github.com/litex-hub/linux-on-litex-vexriscv/issues/239
=> soc_linux.py: Add interrupt switches

make.py
The ULX3S does not have a card detect (CD) pin for the SD interface,
which breaks the sdcard driver in Linux.
This patch changes the ULX3S to use the "spisdcard" interface instead
of the "sdcard" interface.  With this change the SD card works fine
from the BIOS and Linux in SPI-mode.
See also emard/ulx3s#15
Fixes: #203
=> ulx3s: use spisdcard instead of sdcard

make.py
Added support for the existing Cyclone 4 board's bigger brother.  Tested and working (https://github.com/litex-hub/linux-on-litex-vexriscv/issues/258 notwithstanding) - but obviously requires the PR I've raised against litex-boards.
=> Add support for QMTech EP4CE55 board.

make.py
I was able to build the SoC for the Cyclone V 5CEFA2 with 2 CPUs and the decreased size of L2 and SRAM.
Happy if it helps anybody else.
=> Add support for QMTech 5CEFA2 Cyclone V board

make.py
This reduce integrated_sram_size to 0x800 to fix #295.
=> make.py: Reduce integrated_sram_size for de0nano

make.py
For whatever reason, Quartus is unable to infer the integrated_sram memory when its size is not a power of two. This is confirmed using Quartus 20.1.1 and Quartus 18.1. As a result, these boards take excessively long to build and might not fit. The memory size has already been reduced on some of them in an attempt to fix this issue.
To fix this issue for all of them, the size on all Intel boards is reduced to the next lowest power of two. I've confirmed that all boards build, fit, and pass timing using Quartus 20.1.1. I've also confirmed that De10Nano can still boot the demo image.
=> use inferrable power of 2 memory size on Intel boards

soc_linux.py
fixed warning where SoCBuilder.add_interrupt is to be depreciated
=> fix depreciated warnign for add_interrupt

README.md, make.py
This adds support for Machdyne Konfekt and Noir which are now included in the litex-boards repo.
https://github.com/machdyne/konfekt
https://github.com/machdyne/noir
=> support for machdyne konfekt and noir

boards.py, make.py
Reverts litex-hub/linux-on-litex-vexriscv#414
2025-03-10T11:04:30.3945445Z ======================================================================
2025-03-10T11:04:30.3946155Z FAIL: test_boards (test.test_build.TestBuild) [board=ax7020 build test...]
2025-03-10T11:04:30.3946882Z ----------------------------------------------------------------------
2025-03-10T11:04:30.3947218Z Traceback (most recent call last):
2025-03-10T11:04:30.3947756Z   File "/home/runner/work/linux-on-litex-vexriscv/linux-on-litex-vexriscv/test/test_build.py", line 39, in test_boards
2025-03-10T11:04:30.3948285Z     self.board_build_test(board=board)
2025-03-10T11:04:30.3948809Z   File "/home/runner/work/linux-on-litex-vexriscv/linux-on-litex-vexriscv/test/test_build.py", line 18, in board_build_test …
=> Revert "Add support for the Alinx7020 board and enable access to its PS DDR."

boards.py, make.py
Added configuration for colognechip_gatemate_evb, note it does have 8MB of RAM.
This also requires https://github.com/litex-hub/litex-boards/pull/673 to be able to add SD card
=> Added initial colognechip_gatemate_evb support
